/**
 * Default configuration for the 一个电商客服助手，帮助用户查询订单状态、处理退换货申请 agent.
 * Generated by @agentforge/core
 */

import { AgentConfig } from './types';
import { SYSTEM_PROMPT } from './prompts';
import { TOOLS } from './tools';

export const DEFAULT_CONFIG: AgentConfig = {
  model: {
  "provider": "openai",
  "modelName": "gpt-4o",
  "temperature": 0.7,
  "maxTokens": 4096
},
  systemPrompt: SYSTEM_PROMPT,
  tools: TOOLS,
};
