/**
 * Tool definitions for the 一个电商客服助手，帮助用户查询订单状态、处理退换货申请 agent.
 * Generated by @agentforge/core
 */

import { ToolDefinition } from './types';

export const TOOLS: ToolDefinition[] = [
  {
    name: 'query-order',
    description: 'Look up order details by order ID',
    parameters: {
    "type": "object",
    "properties": {
        "orderId": {
            "type": "string",
            "description": "The order ID to look up"
        }
    },
    "required": [
        "orderId"
    ]
},
  },
  {
    name: 'create-refund',
    description: 'Initiate a refund for an order',
    parameters: {
    "type": "object",
    "properties": {
        "orderId": {
            "type": "string",
            "description": "The order ID to refund"
        },
        "reason": {
            "type": "string",
            "description": "Reason for the refund"
        },
        "amount": {
            "type": "number",
            "description": "Refund amount (defaults to full)"
        }
    },
    "required": [
        "orderId",
        "reason"
    ]
},
  },
  {
    name: 'send-notification',
    description: 'Send a notification to a customer',
    parameters: {
    "type": "object",
    "properties": {
        "customerId": {
            "type": "string",
            "description": "Customer ID"
        },
        "message": {
            "type": "string",
            "description": "Notification message"
        },
        "channel": {
            "type": "string",
            "enum": [
                "email",
                "sms",
                "push"
            ],
            "description": "Notification channel"
        }
    },
    "required": [
        "customerId",
        "message"
    ]
},
  }
];
