/**
 * Type definitions for the 一个电商客服助手，帮助用户查询订单状态、处理退换货申请 agent.
 * Generated by @agentforge/core
 */

export interface ToolParameter {
  type: string;
  description?: string;
  enum?: string[];
  items?: ToolParameter;
}

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: {
    type: string;
    properties: Record<string, ToolParameter>;
    required?: string[];
  };
}

export interface AgentConfig {
  model: {
    provider: string;
    modelName: string;
    apiKey?: string;
    temperature?: number;
    maxTokens?: number;
  };
  systemPrompt: string;
  tools?: ToolDefinition[];
  custom?: Record<string, unknown>;
}
